### ISSUE TITLE
NTF Private No work?

### ISSUE THREAD

**Issue by Skepticalzz** [Marco15453/NukeLock#1]
Describe the bug
NTF Private subclass doesn't load when I spawn in as an NTF Private using RA.

To Reproduce
1.  ???

Expected behavior
I expected when I loaded in as an NTF Private it would load me in as the subclass.

Screenshots

Config File
```
name: MTF Striker

affects_roles:
- NtfPrivate

affects_users: {}

any_permissions: {}

string_options:
  GotClassMessage: 
   <b>You are <color=auqa>Striker Specialist Private</color></b>
   
   <i>You are equipped with a shotgun and COM-18 ready for one hell of a fight.</i>
  AbilityCooldownMessage: Your {ability} ability is on cooldown for {seconds} seconds!
  OutOfAbilityUses: Your {ability} is out of uses!
  HelpMessage: Example help message.
  Nickname: Test {name}
  CustomInfo: <color=cyan>Striker Specialist Private</color>

boolean_options:
  Enabled: true
  DisregardHasFF: false
  HasFriendlyFire: false
  DisregardTakesFF: false
  TakesFriendlyFire: false
  GivenOnEscape: false

integer_options:
  MaxHealth: 100
  HealthOnSpawn: 100
  MaxArmor: -1
  ArmorOnSpawn: -1
  MaxAlive: 1

float_options:
  ChanceToGet: 100

spawn_locations:
- Unknown

spawn_items:
  0:
    GunCOM18: 100
  1:
    GunShotgun: 100
  2:
    Radio: 100
  3:
    KeycardNTFOfficer: 100
  4:
    Medkit: 100
  5:
    ArmorCombat: 100

spawn_ammo:
  Ammo12gauge: 24
  Ammo44cal: -1
  Ammo762x39: -1
  Ammo556x45: -1
  Ammo9x19: 56

abilities: []

ability_cooldowns: {}

initial_ability_cooldowns: {}

advanced_ff_rules: []

on_hit_effects: []

roles_that_cant_damage: []

cant_damage: []

on_spawn_effects: []

spawn_parameters: {}
```

Console Logs
 I don't know why I need to considering it says the class loaded successfully but it doesn't work.

Versioning
 - AdvancedSubclassing Version (e.g. 1.0.0-pre013):
 - Exiled Version (e.g. 2.1.3):

Additional context
When I do the command (subclass [id] [subclass name]) it works and loads in as the class I made for the NTF Private which is called MTF Striker. But when I spawn myself in as an NTF Private using RA it doesn't work.
